#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 RiftWii contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Writes src/gxkirby.inc: USB Loader GX's MetaFortress patch for Kirby's
Return to Dream Land (source/patches/kirbypatch.c, "Patch by crediar", ported
to the other regions by dcx2, container12345 and blackb0x), as data.

    py -3 tools/gx_kirby_table.py <usbloadergx>/source/patches/kirbypatch.c src/gxkirby.inc

Each word GX stores becomes one u32: the index of its value in a shared table
in the top byte, the low 24 bits of its address below (every address is in
0x80000000-0x80FFFFFF). The words are kept in GX's order.
"""
import re
import sys

GX_COMMIT = "e25c4f3501ed957b7db73f79c51fdf00715ab2e2"


def main(source, out):
    text = open(source, encoding="utf-8").read()
    regions = []
    current = None
    for line in text.splitlines():
        m = re.search(r'memcmp\(gameid, "(SUK[A-Z]01)", 6\)', line)
        if m:
            current = (m.group(1), [])
            regions.append(current)
            continue
        m = re.match(r"\s*\*\(u32 \*\)0x([0-9A-Fa-f]{8}) = 0x([0-9A-Fa-f]{8});\s*$", line)
        if m:
            if current is None:
                sys.exit("a store outside a region: " + line)
            current[1].append((int(m.group(1), 16), int(m.group(2), 16)))
    if [r[0] for r in regions] != ["SUKE01", "SUKP01", "SUKJ01", "SUKK01"]:
        sys.exit("unexpected regions: %r" % [r[0] for r in regions])
    values = sorted({v for _, words in regions for _, v in words})
    if len(values) > 255:
        sys.exit("too many distinct values")
    index = {v: i for i, v in enumerate(values)}
    lines = [
        "// SPDX-FileCopyrightText: crediar",
        "// SPDX-FileCopyrightText: USB Loader GX contributors <https://github.com/wiidev/usbloadergx>",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by tools/gx_kirby_table.py from USB Loader GX",
        "// (https://github.com/wiidev/usbloadergx at commit " + GX_COMMIT + "),",
        "// source/patches/kirbypatch.c: the MetaFortress patch for Kirby's Return to",
        "// Dream Land (patch by crediar; ported by dcx2, container12345 and blackb0x).",
        "// GPL-3.0 (USB Loader GX's licence). Do not edit; regenerate.",
        "",
        "const std::uint32_t kKirbyValues[] = {",
    ]
    for i in range(0, len(values), 6):
        lines.append("    " + " ".join("0x%08Xu," % v for v in values[i:i + 6]))
    lines.append("};")
    for gid, words in regions:
        lines.append("")
        lines.append("const std::uint32_t kKirby%s[] = {  // %d words" % (gid, len(words)))
        packed = []
        for address, value in words:
            if address & 0xFF000000 != 0x80000000 or address & 3:
                sys.exit("address out of range: %08X" % address)
            packed.append((index[value] << 24) | (address & 0x00FFFFFF))
        for i in range(0, len(packed), 8):
            lines.append("    " + " ".join("0x%08Xu," % p for p in packed[i:i + 8]))
        lines.append("};")
    lines.append("")
    open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print("%d values; %s" % (len(values), ", ".join("%s %d" % (g, len(w)) for g, w in regions)))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
