#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 RiftWii contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""The games with no online play, from GameTDB's database, for the game
page's Online server row (src/offlinegames.cpp).

GameTDB (https://www.gametdb.com) lists each game's online features under
<wi-fi players="N"><feature>...</feature></wi-fi>. A game counts as having
no online play only when GameTDB says so plainly: no online players and
no feature that went through Nintendo Wi-Fi Connection (score, download,
wiimmfi). "online" alone is kept as online (Boom Blox's level sharing),
unless the only other feature is the Message Board (WiiConnect24: Wii
Sports Resort). Games GameTDB does not know, and its custom entries
(hacks, mod distributions), are left out: their row stays as it is.

Codes are the IDs' first four characters (game and region); a code is
listed only when every game with it has no online play.

    python tools/make_offline_games.py wiitdb.xml src/offlinegames.inc

wiitdb.xml is in https://www.gametdb.com/wiitdb.zip.
"""

import argparse
import xml.etree.ElementTree as ET

WFC_FEATURES = {"score", "download", "wiimmfi"}


def has_online(game):
    wifi = game.find("wi-fi")
    if wifi is None:
        return False
    players = wifi.get("players", "0")
    if players.isdigit() and int(players) > 0:
        return True
    features = {f.text for f in wifi.findall("feature") if f.text}
    if features & WFC_FEATURES:
        return True
    return "online" in features and "messageboard" not in features


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("wiitdb")
    parser.add_argument("out")
    args = parser.parse_args()
    root = ET.parse(args.wiitdb).getroot()
    version = root.find("WiiTDB").get("version", "")
    offline, online = set(), set()
    for game in root.iter("game"):
        gid = (game.findtext("id") or "").strip()
        if (game.findtext("type") or "").strip() or len(gid) != 6 or not gid.isalnum():
            continue  # custom entries, WiiWare and Virtual Console
        (online if has_online(game) else offline).add(gid[:4].upper())
    codes = sorted(offline - online)
    with open(args.out, "w", encoding="ascii", newline="\n") as f:
        f.write("// SPDX-FileCopyrightText: 2026 RiftWii contributors\n")
        f.write("// SPDX-License-Identifier: GPL-3.0-or-later\n")
        f.write("// Generated by tools/make_offline_games.py from GameTDB's wiitdb.xml\n")
        f.write("// (https://www.gametdb.com), version %s: %d codes.\n" % (version, len(codes)))
        for i in range(0, len(codes), 12):
            f.write(" ".join('"%s"' % c for c in codes[i:i + 12]) + "\n")
    print("%d game codes with no online play (%d with online)" % (len(codes), len(online)))


if __name__ == "__main__":
    main()
