#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Writes wii/sdcard_qr.hpp: the QR code on the "needs an SD card" screen
(wii/rift_menu.cpp, MenuNeedsSd), as rows of '#' and '.', so the menu
draws it without a QR encoder of its own.

Needs segno (pip install segno).

    python tools/make_qr.py
"""

import pathlib

import segno

URL = "https://www.amazon.com/s?k=16gb+sd+card"
OUT = pathlib.Path(__file__).resolve().parent.parent / "wii" / "sdcard_qr.hpp"


def main():
    qr = segno.make_qr(URL, error="m")
    rows = ["".join("#" if bit else "." for bit in row) for row in qr.matrix]
    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by tools/make_qr.py; do not edit.",
        "#pragma once",
        "",
        f"// {URL}",
        f"constexpr int kSdCardQrSize = {len(rows)};",
        "constexpr const char* kSdCardQr[kSdCardQrSize] = {",
    ]
    lines += [f'    "{row}",' for row in rows]
    lines += ["};", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{OUT}: version {qr.version}, {len(rows)}x{len(rows)}")


if __name__ == "__main__":
    main()
